name: Deploy Lambda to AWS

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      lambda_name:
        required: true
        type: string

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install Python module
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.file_path }}/requirements.txt -t ./${{ inputs.file_path }}

      - name: Python files to Zip file
        run: |
          zip Build_${{ inputs.lambda_name }}.zip -j ${{ inputs.file_path }}/*;

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_${{ inputs.lambda_name }}
          path: Build_${{ inputs.lambda_name }}.zip
          if-no-files-found: error

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda Build.zip
        uses: actions/download-artifact@v3
        with:
          name: build_${{ inputs.lambda_name }}

      - name: Upload to S3
        run: aws s3 cp Build_${{ inputs.lambda_name }}.zip s3://solvedac-readme-stats--build/Build_${{ inputs.lambda_name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy ${{ inputs.lambda_name }}
        run: aws lambda update-function-code --function-name ${{ inputs.lambda_name }} --s3-bucket solvedac-readme-stats--build --s3-key Build_${{ inputs.lambda_name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
